import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { test } from "node:test";
import { loadDelegateConfig } from "../config.ts";
import { AUDIT_CHECKS, parseAuditCall, SnapshotAudits } from "../snapshot-audit.ts";
import { repositoryFor, snapshotEnabled, snapshotNeedsAudit } from "../snapshots.ts";

test("first-use safety audit requires consent and unchanged best-effort results, without capturing audit inputs", async () => {
	const dir = mkdtempSync(join(tmpdir(), "delegate-snapshot-audit-"));
	const repoPath = join(dir, "repo"), storage = join(dir, "snapshots"), userPath = join(dir, "delegate.json");
	mkdirSync(repoPath);
	const git = (...args: string[]) => execFileSync("git", args, { cwd: repoPath, encoding: "utf8" });
	git("init", "-q", "-b", "main");
	writeFileSync(join(repoPath, "source"), "source contents must never enter the generated audit prompt\n");
	git("add", "."); git("-c", "user.name=Test", "-c", "user.email=test@invalid", "commit", "-qm", "base");
	const repo = (await repositoryFor(repoPath))!;
	const paths = { shippedPath: new URL("../config.json", import.meta.url).pathname, userPath };
	writeFileSync(userPath, JSON.stringify({ snapshots: { directory: storage, defaultEnabled: true, repositories: {} } }));
	const config = loadDelegateConfig(paths), messages: string[] = [], notices: string[] = [];
	let yes = false, confirms = 0, sessionId = "session-one", idle = true;
	const pi: any = { getActiveTools: () => ["delegate"], sendUserMessage: (message: string) => messages.push(message) };
	const ctx: any = { cwd: repoPath, hasUI: true, model: { id: "selected" }, isIdle: () => idle, sessionManager: { getSessionId: () => sessionId },
		ui: { confirm: async () => { confirms++; assert.equal(config.snapshots.repositories[repo.configKey], false); return yes; }, notify: (message: string) => notices.push(message) } };
	const manager = new SnapshotAudits(pi, config, paths, dir), signal = new AbortController().signal;
	const passed = { verdict: "passed" as const, checked: [...AUDIT_CHECKS], issues: [] };
	const begin = async () => {
		yes = true; assert.equal(await manager.request(ctx, repo, signal), true);
		assert.equal(snapshotEnabled(repo, config.snapshots), false);
		const prompt = messages.at(-1)!;
		assert.ok(!prompt.includes("source contents must never"));
		assert.match(prompt, /Do not delegate, create snapshots/);
		assert.equal(existsSync(storage), false, "the audit never creates snapshot storage");
		return prompt.match(/Audit ID: ([a-f0-9-]{36})/)![1];
	};
	try {
		assert.equal(snapshotEnabled(repo, config.snapshots), false);
		assert.equal(snapshotNeedsAudit(repo, config.snapshots), true);
		assert.equal(await manager.request(ctx, repo, signal), false);
		assert.equal(messages.length, 0); assert.equal(confirms, 1);
		assert.equal(snapshotNeedsAudit(repo, config.snapshots), false, "decline persists an explicit disable");
		assert.equal(JSON.parse(readFileSync(userPath, "utf8")).snapshots.repositories[repo.configKey], false);
		yes = true; idle = false;
		assert.equal(await manager.request(ctx, repo, signal), false, "busy-parent consent never queues a follow-up audit");
		assert.equal(messages.length, 0); assert.equal(manager.active, false);
		assert.match(notices.at(-1)!, /parent agent is busy/);
		idle = true;
		let id = await begin();
		assert.throws(() => parseAuditCall({ auditId: id, auditResult: { ...passed, issues: ["redacted finding"] } }), /blocking issues/);
		assert.throws(() => parseAuditCall({ auditId: id, auditResult: { ...passed, checked: [] } }), /substantive checks/);
		const bestEffort = { ...passed, checked: ["source"], warnings: ["docs/images: pixel content unexamined"] };
		assert.deepEqual(parseAuditCall({ auditId: id, auditResult: bestEffort })!.auditResult, bestEffort);
		assert.throws(() => parseAuditCall({ auditId: id, auditResult: { ...bestEffort, warnings: [" "] } }), /Invalid snapshot audit/);
		assert.throws(() => parseAuditCall({ auditId: id, auditResult: passed, kind: "review" }), /cannot be combined/);
		assert.equal(parseAuditCall({ auditId: null, auditResult: " " }), undefined);
		assert.equal(parseAuditCall({ auditId: id, auditResult: passed, jobId: null })!.auditId, id);
		await assert.rejects(manager.submit(ctx, "00000000-0000-0000-0000-000000000000", passed), /No matching/);
		assert.match(await manager.submit(ctx, id, { verdict: "blocked", checked: ["source"], issues: ["redacted finding"] }), /remains disabled/);
		assert.equal(snapshotEnabled(repo, config.snapshots), false);
		await assert.rejects(manager.submit(ctx, id, passed), /No matching/);
		id = await begin();
		assert.match(await manager.submit(ctx, id, { verdict: "incomplete", checked: ["source"], issues: [] }), /remains disabled/);
		id = await begin();
		manager.endTurn();
		await assert.rejects(manager.submit(ctx, id, passed), /finished its turn without submitting/);
		assert.match(notices.at(-1)!, /incomplete/);
		id = await begin();
		writeFileSync(join(repoPath, "source"), "changed after consent\n");
		await assert.rejects(manager.submit(ctx, id, passed), /Repository changed/);
		assert.equal(snapshotEnabled(repo, config.snapshots), false);
		git("add", "source"); git("-c", "user.name=Test", "-c", "user.email=test@invalid", "commit", "-qm", "changed source");
		writeFileSync(join(repoPath, ".git", "shallow"), git("rev-parse", "HEAD"));
		id = await begin();
		rmSync(join(repoPath, ".git", "shallow"));
		await assert.rejects(manager.submit(ctx, id, passed), /Repository changed/, "newly reachable history invalidates an audit even with unchanged HEAD/source");
		id = await begin();
		sessionId = "other-session";
		await assert.rejects(manager.submit(ctx, id, passed), /session changed after audit approval/);
		sessionId = "session-one"; manager.cancel();
		id = await begin();
		const cancelled = manager.submit(ctx, id, passed); manager.cancel();
		await assert.rejects(cancelled, /abort/i);
		assert.equal(snapshotEnabled(repo, config.snapshots), false);
		id = await begin();
		const disk = JSON.parse(readFileSync(userPath, "utf8"));
		disk.snapshots.directory = join(dir, "changed-storage"); writeFileSync(userPath, JSON.stringify(disk));
		await assert.rejects(manager.submit(ctx, id, passed), /changed on disk/);
		assert.equal(snapshotEnabled(repo, config.snapshots), false);
		writeFileSync(userPath, JSON.stringify({ snapshots: config.snapshots }));
		id = await begin();
		const accepted = manager.submit(ctx, id, bestEffort);
		await assert.rejects(manager.submit(ctx, id, passed), /No matching/);
		const message = await accepted;
		assert.match(message, /No secret leak was demonstrated; capture enabled/);
		assert.match(message, /Checked 1\/5 areas/);
		assert.match(message, /Warnings:\n- docs\/images: pixel content unexamined/);
		assert.equal(snapshotEnabled(repo, config.snapshots), true);
		assert.equal(JSON.parse(readFileSync(userPath, "utf8")).snapshots.repositories[repo.configKey], true);
		assert.equal(existsSync(storage), false, "even a passed audit must not itself capture");
	} finally { manager.cancel(); rmSync(dir, { recursive: true, force: true }); }
});
